"""The practice range — the marshes the dog hunts when nothing is at stake.

These live in code, not in a data file, for one hard reason: the skill
export ships only the runtime tree (engine, game, scripts, strategy),
so anything under tests/ is stripped on install. The ghost hunt is the
whole first-run experience, and it cannot depend on a file that will
not be there.

A marsh is the shape FixtureFeed expects: a weather state, the ducks
on the water, and a price series per duck so exits can play out.
"""

from __future__ import annotations

import json
import os
from typing import Any

MARSHES: dict[str, dict[str, Any]] = {'calm_day': {'weather': {'state': 'Calm'},
              'scout': [{'token': 'DUCKmint111111111111111111111111111111111111',
                         'symbol': 'DUCK',
                         'chain': 'solana',
                         'heat': 82,
                         'liquidity_usd': 61000,
                         'age_minutes': 95,
                         'top10_holders_pct': 34,
                         'graduated': True,
                         'launchpad': 'pump.fun',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True,
                         'price_usd': 0.001},
                        {'token': 'PONDmint11111111111111111111111111111111111',
                         'symbol': 'POND',
                         'chain': 'solana',
                         'heat': 77,
                         'liquidity_usd': 40000,
                         'age_minutes': 300,
                         'top10_holders_pct': 71,
                         'launchpad': 'pump.fun',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True},
                        {'token': 'FAKEmint11111111111111111111111111111111111',
                         'symbol': 'DOGE2',
                         'chain': 'solana',
                         'heat': 74,
                         'liquidity_usd': 90000,
                         'age_minutes': 60,
                         'top10_holders_pct': 22,
                         'copycat_flag': True,
                         'launchpad': 'moonshot',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True},
                        {'token': 'TRAPmint11111111111111111111111111111111111',
                         'symbol': 'SAFEGEM',
                         'chain': 'solana',
                         'heat': 73,
                         'liquidity_usd': 55000,
                         'age_minutes': 120,
                         'top10_holders_pct': 18,
                         'honeypot_flag': True,
                         'launchpad': 'bonk.fun',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True},
                        {'token': 'PUDDLEmint111111111111111111111111111111111',
                         'symbol': 'PUDDLE',
                         'chain': 'solana',
                         'heat': 71,
                         'liquidity_usd': 9000,
                         'age_minutes': 45,
                         'top10_holders_pct': 30,
                         'launchpad': 'pump.fun',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True},
                        {'token': 'COLDmint11111111111111111111111111111111111',
                         'symbol': 'COLD',
                         'chain': 'solana',
                         'heat': 41,
                         'liquidity_usd': 80000,
                         'age_minutes': 200,
                         'top10_holders_pct': 25,
                         'launchpad': 'moonshot',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True},
                        {'token': 'NESTmint11111111111111111111111111111111111',
                         'symbol': 'NEST',
                         'chain': 'solana',
                         'heat': 88,
                         'liquidity_usd': 30000,
                         'age_minutes': 6,
                         'top10_holders_pct': 15,
                         'launchpad': 'pump.fun',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': True,
                         'token2022_clean': True},
                        {'token': 'FROZENmint111111111111111111111111111111111',
                         'symbol': 'ICEDUCK',
                         'chain': 'solana',
                         'heat': 75,
                         'liquidity_usd': 47000,
                         'age_minutes': 90,
                         'top10_holders_pct': 28,
                         'launchpad': 'bonk.fun',
                         'mint_authority_revoked': True,
                         'freeze_authority_revoked': False,
                         'token2022_clean': True}],
              'prices': {'DUCKmint111111111111111111111111111111111111': [0.001,
                                                                          0.0021,
                                                                          0.0021,
                                                                          0.0041,
                                                                          0.0041,
                                                                          0.0041]}},
 'no_duck_day': {'weather': {'state': 'Brisk'},
                 'scout': [{'token': 'T1',
                            'symbol': 'WAGMI',
                            'chain': 'solana',
                            'heat': 91,
                            'liquidity_usd': 8000,
                            'age_minutes': 40,
                            'top10_holders_pct': 20,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T2',
                            'symbol': 'MOONBOI',
                            'chain': 'solana',
                            'heat': 88,
                            'liquidity_usd': 11000,
                            'age_minutes': 55,
                            'top10_holders_pct': 25,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T3',
                            'symbol': 'GIGA',
                            'chain': 'solana',
                            'heat': 86,
                            'liquidity_usd': 4000,
                            'age_minutes': 30,
                            'top10_holders_pct': 31,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T4',
                            'symbol': 'PEPE9',
                            'chain': 'solana',
                            'heat': 84,
                            'liquidity_usd': 14000,
                            'age_minutes': 70,
                            'top10_holders_pct': 18,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T5',
                            'symbol': 'SOLDOG',
                            'chain': 'solana',
                            'heat': 83,
                            'liquidity_usd': 6000,
                            'age_minutes': 25,
                            'top10_holders_pct': 40,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T6',
                            'symbol': 'CHAD',
                            'chain': 'solana',
                            'heat': 82,
                            'liquidity_usd': 18000,
                            'age_minutes': 90,
                            'top10_holders_pct': 22,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T7',
                            'symbol': 'FUDCAT',
                            'chain': 'solana',
                            'heat': 81,
                            'liquidity_usd': 12000,
                            'age_minutes': 110,
                            'top10_holders_pct': 35,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T8',
                            'symbol': 'SNIPE',
                            'chain': 'solana',
                            'heat': 79,
                            'liquidity_usd': 16000,
                            'age_minutes': 130,
                            'top10_holders_pct': 44,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'T9',
                            'symbol': 'LAMBO',
                            'chain': 'solana',
                            'heat': 78,
                            'liquidity_usd': 21000,
                            'age_minutes': 160,
                            'top10_holders_pct': 12,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'TA',
                            'symbol': 'BONK2',
                            'chain': 'solana',
                            'heat': 90,
                            'liquidity_usd': 70000,
                            'age_minutes': 80,
                            'top10_holders_pct': 20,
                            'copycat_flag': True,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'TB',
                            'symbol': 'WIF2',
                            'chain': 'solana',
                            'heat': 85,
                            'liquidity_usd': 52000,
                            'age_minutes': 100,
                            'top10_holders_pct': 27,
                            'copycat_flag': True,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'TC',
                            'symbol': 'PENGU2',
                            'chain': 'solana',
                            'heat': 80,
                            'liquidity_usd': 33000,
                            'age_minutes': 140,
                            'top10_holders_pct': 30,
                            'copycat_flag': True,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'TD',
                            'symbol': '100XGEM',
                            'chain': 'solana',
                            'heat': 87,
                            'liquidity_usd': 45000,
                            'age_minutes': 65,
                            'top10_holders_pct': 24,
                            'honeypot_flag': True,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True},
                           {'token': 'TE',
                            'symbol': 'RUGME',
                            'chain': 'solana',
                            'heat': 76,
                            'liquidity_usd': 38000,
                            'age_minutes': 85,
                            'top10_holders_pct': 29,
                            'honeypot_flag': True,
                            'mint_authority_revoked': True,
                            'freeze_authority_revoked': True,
                            'token2022_clean': True}],
                 'prices': {}},
 'storm_bust': {'weather': {'state': 'Storm'},
                'scout': [{'token': 'GALEmint11111111111111111111111111111111111',
                           'symbol': 'GALE',
                           'chain': 'solana',
                           'heat': 93,
                           'liquidity_usd': 48000,
                           'age_minutes': 50,
                           'top10_holders_pct': 26,
                           'launchpad': 'pump.fun',
                           'mint_authority_revoked': True,
                           'freeze_authority_revoked': True,
                           'token2022_clean': True,
                           'price_usd': 0.002},
                          {'token': 'SQUALLmint111111111111111111111111111111111',
                           'symbol': 'SQUALL',
                           'chain': 'solana',
                           'heat': 89,
                           'liquidity_usd': 39000,
                           'age_minutes': 75,
                           'top10_holders_pct': 33,
                           'launchpad': 'bonk.fun',
                           'mint_authority_revoked': True,
                           'freeze_authority_revoked': True,
                           'token2022_clean': True,
                           'price_usd': 0.0005},
                          {'token': 'SLEETmint1111111111111111111111111111111111',
                           'symbol': 'SLEET',
                           'chain': 'solana',
                           'heat': 71,
                           'liquidity_usd': 12000,
                           'age_minutes': 33,
                           'top10_holders_pct': 41,
                           'launchpad': 'pump.fun',
                           'mint_authority_revoked': True,
                           'freeze_authority_revoked': True,
                           'token2022_clean': True}],
                'prices': {'GALEmint11111111111111111111111111111111111': [0.002,
                                                                           0.0004,
                                                                           0.0004,
                                                                           0.0004],
                           'SQUALLmint111111111111111111111111111111111': [0.0005,
                                                                           0.0001,
                                                                           0.0001,
                                                                           0.0001]}}}


DEFAULT = "calm_day"


def load(name_or_path: str | None = None) -> dict[str, Any]:
    """Resolve a practice marsh by name, or read one from a file.

    Names come from MARSHES and always work, installed or not. A path
    is still accepted so anyone can hunt a marsh of their own making.
    """
    key = name_or_path or DEFAULT
    if key in MARSHES:
        return MARSHES[key]
    if os.path.exists(key):
        with open(key, "r", encoding="utf-8") as fh:
            return json.load(fh)
    known = ", ".join(sorted(MARSHES))
    raise SystemExit(
        f"No such practice marsh: {key!r}. Known marshes: {known} "
        f"(or give a path to a marsh file)."
    )
